import { ForbiddenException, Inject, Injectable, NotFoundException } from '@nestjs/common';
import { and, asc, desc, eq, gte, inArray } from 'drizzle-orm';
import { DATABASE, Database } from '../../database/database.module';
import { invoices, invoiceItems, payments } from '../../database/schema/billing';
import { visitDiagnoses, visits, diagnoses } from '../../database/schema/clinical';
import { appointments, clinicServices, doctors, queueEntries } from '../../database/schema/operations';
import { patients } from '../../database/schema/patients';
import { medicines, prescriptionItems, prescriptions } from '../../database/schema/prescribing';
import { users } from '../../database/schema';
import { AppointmentsService } from '../appointments/appointments.service';
import { AuditContext, AuditService } from '../audit/audit.service';
import { PatientBookAppointmentDto } from './patient-portal.dto';

@Injectable()
export class PatientPortalService {
  constructor(@Inject(DATABASE) private readonly db: Database, private readonly appointmentsService: AppointmentsService, private readonly audit: AuditService) {}
  private async patientFor(userId: string) { const [patient] = await this.db.select().from(patients).where(eq(patients.portalUserId, userId)).limit(1); if (!patient) throw new ForbiddenException('Patient account is not linked to a patient profile'); return patient; }
  async profile(userId: string) { return this.patientFor(userId); }
  async references() { const [doctorRows, serviceRows] = await Promise.all([this.db.select({ id: doctors.id, fullName: users.fullName, specialty: doctors.specialty }).from(doctors).innerJoin(users, eq(doctors.userId, users.id)).where(and(eq(doctors.isActive, true), eq(users.isActive, true))).orderBy(users.fullName), this.db.select({ id: clinicServices.id, name: clinicServices.name, durationMinutes: clinicServices.durationMinutes, price: clinicServices.price }).from(clinicServices).where(eq(clinicServices.isActive, true)).orderBy(clinicServices.name)]); return { doctors: doctorRows, services: serviceRows }; }
  async appointments(userId: string) { const patient = await this.patientFor(userId); return this.db.select({ id: appointments.id, appointmentDate: appointments.appointmentDate, startTime: appointments.startTime, endTime: appointments.endTime, status: appointments.status, notes: appointments.notes, doctorName: users.fullName, specialty: doctors.specialty, serviceName: clinicServices.name }).from(appointments).innerJoin(doctors, eq(appointments.doctorId, doctors.id)).innerJoin(users, eq(doctors.userId, users.id)).innerJoin(clinicServices, eq(appointments.serviceId, clinicServices.id)).where(eq(appointments.patientId, patient.id)).orderBy(desc(appointments.appointmentDate), desc(appointments.startTime)).limit(100); }
  async book(userId: string, dto: PatientBookAppointmentDto, context: AuditContext) { const patient = await this.patientFor(userId); return this.appointmentsService.create({ patientId: patient.id, ...dto }, context); }
  async cancel(userId: string, id: string, context: AuditContext) { const patient = await this.patientFor(userId); const [appointment] = await this.db.select().from(appointments).where(and(eq(appointments.id, id), eq(appointments.patientId, patient.id))).limit(1); if (!appointment) throw new NotFoundException('Appointment not found'); const [updated] = await this.db.update(appointments).set({ status: 'CANCELLED', updatedAt: new Date() }).where(and(eq(appointments.id, id), eq(appointments.patientId, patient.id), inArray(appointments.status, ['BOOKED', 'CONFIRMED']))).returning(); if (!updated) throw new ForbiddenException('This appointment can no longer be cancelled'); await this.audit.log({ ...context, action: 'APPOINTMENT_PATIENT_CANCEL', entity: 'appointments', entityId: id, oldValue: appointment, newValue: updated }); return updated; }
  async queue(userId: string) { const patient = await this.patientFor(userId); const today = new Date().toISOString().slice(0, 10); const [entry] = await this.db.select({ id: queueEntries.id, queueNumber: queueEntries.queueNumber, status: queueEntries.status, checkedInAt: queueEntries.checkedInAt, doctorName: users.fullName }).from(queueEntries).innerJoin(doctors, eq(queueEntries.doctorId, doctors.id)).innerJoin(users, eq(doctors.userId, users.id)).where(and(eq(queueEntries.patientId, patient.id), eq(queueEntries.queueDate, today), inArray(queueEntries.status, ['WAITING', 'CALLED', 'IN_CONSULTATION']))).orderBy(desc(queueEntries.checkedInAt)).limit(1); return entry ?? null; }
  async history(userId: string) { const patient = await this.patientFor(userId); const rows = await this.db.select({ id: visits.id, startedAt: visits.startedAt, completedAt: visits.completedAt, status: visits.status, chiefComplaint: visits.chiefComplaint, treatmentPlan: visits.treatmentPlan, doctorName: users.fullName }).from(visits).innerJoin(doctors, eq(visits.doctorId, doctors.id)).innerJoin(users, eq(doctors.userId, users.id)).where(eq(visits.patientId, patient.id)).orderBy(desc(visits.startedAt)).limit(100); return Promise.all(rows.map(async (visit) => ({ ...visit, diagnoses: await this.db.select({ code: diagnoses.icd10Code, name: diagnoses.name, isPrimary: visitDiagnoses.isPrimary }).from(visitDiagnoses).innerJoin(diagnoses, eq(visitDiagnoses.diagnosisId, diagnoses.id)).where(eq(visitDiagnoses.visitId, visit.id)).orderBy(desc(visitDiagnoses.isPrimary)) }))); }
  async prescriptions(userId: string) { const patient = await this.patientFor(userId); const rows = await this.db.select({ id: prescriptions.id, prescriptionNumber: prescriptions.prescriptionNumber, status: prescriptions.status, createdAt: prescriptions.createdAt, doctorName: users.fullName }).from(prescriptions).innerJoin(doctors, eq(prescriptions.doctorId, doctors.id)).innerJoin(users, eq(doctors.userId, users.id)).where(eq(prescriptions.patientId, patient.id)).orderBy(desc(prescriptions.createdAt)).limit(100); return Promise.all(rows.map(async (prescription) => ({ ...prescription, items: await this.db.select({ medicineName: medicines.name, dosage: prescriptionItems.dosage, frequency: prescriptionItems.frequency, route: prescriptionItems.route, durationDays: prescriptionItems.durationDays, quantity: prescriptionItems.quantity, instructions: prescriptionItems.instructions }).from(prescriptionItems).innerJoin(medicines, eq(prescriptionItems.medicineId, medicines.id)).where(eq(prescriptionItems.prescriptionId, prescription.id)) }))); }
  async invoices(userId: string) { const patient = await this.patientFor(userId); return this.db.select({ id: invoices.id, invoiceNumber: invoices.invoiceNumber, invoiceDate: invoices.invoiceDate, grandTotal: invoices.grandTotal, amountPaid: invoices.amountPaid, status: invoices.status }).from(invoices).where(eq(invoices.patientId, patient.id)).orderBy(desc(invoices.invoiceDate)).limit(100); }
  async invoice(userId: string, id: string) { const patient = await this.patientFor(userId); const [invoice] = await this.db.select().from(invoices).where(and(eq(invoices.id, id), eq(invoices.patientId, patient.id))).limit(1); if (!invoice) throw new NotFoundException('Invoice not found'); const [items, receiptPayments] = await Promise.all([this.db.select().from(invoiceItems).where(eq(invoiceItems.invoiceId, id)), this.db.select().from(payments).where(eq(payments.invoiceId, id)).orderBy(desc(payments.paidAt))]); return { ...invoice, balance: (Number(invoice.grandTotal) - Number(invoice.amountPaid)).toFixed(2), items, payments: receiptPayments }; }
  async dashboard(userId: string) { const patient = await this.patientFor(userId); const today = new Date().toISOString().slice(0, 10); const [upcoming, currentQueue, recentVisits, recentPrescriptions, outstanding] = await Promise.all([this.db.select({ id: appointments.id, appointmentDate: appointments.appointmentDate, startTime: appointments.startTime, status: appointments.status, doctorName: users.fullName, serviceName: clinicServices.name }).from(appointments).innerJoin(doctors, eq(appointments.doctorId, doctors.id)).innerJoin(users, eq(doctors.userId, users.id)).innerJoin(clinicServices, eq(appointments.serviceId, clinicServices.id)).where(and(eq(appointments.patientId, patient.id), gte(appointments.appointmentDate, today), inArray(appointments.status, ['BOOKED', 'CONFIRMED']))).orderBy(asc(appointments.appointmentDate), asc(appointments.startTime)).limit(1), this.queue(userId), this.db.select({ id: visits.id, startedAt: visits.startedAt, chiefComplaint: visits.chiefComplaint }).from(visits).where(eq(visits.patientId, patient.id)).orderBy(desc(visits.startedAt)).limit(3), this.db.select({ id: prescriptions.id, prescriptionNumber: prescriptions.prescriptionNumber, status: prescriptions.status, createdAt: prescriptions.createdAt }).from(prescriptions).where(eq(prescriptions.patientId, patient.id)).orderBy(desc(prescriptions.createdAt)).limit(3), this.db.select({ id: invoices.id, invoiceNumber: invoices.invoiceNumber, grandTotal: invoices.grandTotal, amountPaid: invoices.amountPaid, status: invoices.status }).from(invoices).where(and(eq(invoices.patientId, patient.id), inArray(invoices.status, ['PENDING', 'PARTIAL']))).orderBy(desc(invoices.invoiceDate)).limit(5)]); return { profile: patient, upcomingAppointment: upcoming[0] ?? null, currentQueue, recentVisits, recentPrescriptions, outstandingInvoices: outstanding }; }
}
