import { zodResolver } from '@hookform/resolvers/zod';
import { Button, Grid, Group, Modal, NumberInput, Stack } from '@mantine/core';
import { notifications } from '@mantine/notifications';
import { Controller, useForm } from 'react-hook-form';
import { useAddMeasurement } from '../api/patient-queries';
import { MeasurementFormValues, measurementSchema } from '../schema';

type Props={patientId:string;opened:boolean;onClose:()=>void};
const defaults:MeasurementFormValues={systolicBloodPressure:120,diastolicBloodPressure:80,weightKg:60,heightCm:165,temperature:'',heartRate:'',respiratoryRate:'',oxygenSaturation:''};
export function MeasurementModal({patientId,opened,onClose}:Props){const mutation=useAddMeasurement();const{control,handleSubmit,reset,formState:{errors}}=useForm<MeasurementFormValues>({resolver:zodResolver(measurementSchema),defaultValues:defaults});const submit=handleSubmit(async(values)=>{try{const optional=(value:number|'')=>value===''?undefined:value;await mutation.mutateAsync({id:patientId,input:{systolicBloodPressure:values.systolicBloodPressure,diastolicBloodPressure:values.diastolicBloodPressure,weightKg:values.weightKg,heightCm:values.heightCm,temperature:optional(values.temperature),heartRate:optional(values.heartRate),respiratoryRate:optional(values.respiratoryRate),oxygenSaturation:optional(values.oxygenSaturation)}});notifications.show({color:'teal',message:'Measurement added to patient history'});reset(defaults);onClose();}catch{notifications.show({color:'red',message:'Review measurement values and try again'});}});return <Modal opened={opened} onClose={onClose} title="Add measurement"><form onSubmit={submit}><Stack><Grid><Grid.Col span={6}><Controller name="systolicBloodPressure" control={control} render={({field})=><NumberInput required label="Systolic BP" suffix=" mmHg" value={field.value} onChange={field.onChange} error={errors.systolicBloodPressure?.message}/>} /></Grid.Col><Grid.Col span={6}><Controller name="diastolicBloodPressure" control={control} render={({field})=><NumberInput required label="Diastolic BP" suffix=" mmHg" value={field.value} onChange={field.onChange} error={errors.diastolicBloodPressure?.message}/>} /></Grid.Col><Grid.Col span={6}><Controller name="weightKg" control={control} render={({field})=><NumberInput required label="Weight" suffix=" kg" decimalScale={1} value={field.value} onChange={field.onChange} error={errors.weightKg?.message}/>} /></Grid.Col><Grid.Col span={6}><Controller name="heightCm" control={control} render={({field})=><NumberInput required label="Height" suffix=" cm" decimalScale={1} value={field.value} onChange={field.onChange} error={errors.heightCm?.message}/>} /></Grid.Col>{([['temperature','Temperature',' °C'],['heartRate','Heart rate',' bpm'],['respiratoryRate','Respiratory rate',' /min'],['oxygenSaturation','SpO₂','%']] as const).map(([name,label,suffix])=><Grid.Col span={6} key={name}><Controller name={name} control={control} render={({field})=><NumberInput label={label} suffix={suffix} value={field.value} onChange={field.onChange}/>} /></Grid.Col>)}</Grid><Group justify="flex-end"><Button variant="default" onClick={onClose}>Cancel</Button><Button type="submit" loading={mutation.isPending}>Add measurement</Button></Group></Stack></form></Modal>}
