import { useEffect, useState } from 'react';
import { zodResolver } from '@hookform/resolvers/zod';
import { Alert, Button, Divider, Grid, Group, Modal, NumberInput, Paper, Select, Stack, Text, TextInput, Textarea, Title } from '@mantine/core';
import { DateInput } from '@mantine/dates';
import { notifications } from '@mantine/notifications';
import { Controller, useForm } from 'react-hook-form';
import { format } from 'date-fns';
import { patientApi } from '../api/patient-api';
import { useCreatePatient, useUpdatePatient } from '../api/patient-queries';
import { patientFormSchema, PatientFormValues } from '../schema';
import type { CreatePatientInput, Patient, PossibleDuplicate, UpdatePatientInput } from '../types';

type Props = { opened:boolean;onClose:()=>void;patient:Patient|null;onOpenExisting:(id:string)=>void };
const emptyValues:PatientFormValues = {fullName:'',nik:'',dateOfBirth:'',gender:'MALE',phone:'',email:'',address:'',bloodType:'UNKNOWN',emergencyContactName:'',emergencyContactPhone:'',emergencyContactRelationship:'',paymentType:'SELF_PAY',insuranceProvider:'',insuranceMemberNumber:'',status:'ACTIVE',systolicBloodPressure:120,diastolicBloodPressure:80,weightKg:60,heightCm:165};
const optional=(value:string)=>value.trim()||undefined;

export function PatientFormModal({opened,onClose,patient,onOpenExisting}:Props) {
  const createPatient=useCreatePatient(); const updatePatient=useUpdatePatient(); const[duplicates,setDuplicates]=useState<PossibleDuplicate[]>([]);const[confirmed,setConfirmed]=useState(false);
  const {register,control,handleSubmit,reset,watch,formState:{errors,isSubmitting}}=useForm<PatientFormValues>({resolver:zodResolver(patientFormSchema),defaultValues:emptyValues});
  const paymentType=watch('paymentType');
  useEffect(()=>{if(opened){setDuplicates([]);setConfirmed(false);reset(patient?{...emptyValues,fullName:patient.fullName,nik:patient.nik??'',dateOfBirth:patient.dateOfBirth,gender:patient.gender,phone:patient.phone,email:patient.email??'',address:patient.address,bloodType:patient.bloodType??'UNKNOWN',emergencyContactName:patient.emergencyContactName??'',emergencyContactPhone:patient.emergencyContactPhone??'',emergencyContactRelationship:patient.emergencyContactRelationship??'',paymentType:patient.paymentType??'SELF_PAY',insuranceProvider:patient.insuranceProvider??'',insuranceMemberNumber:patient.insuranceMemberNumber??'',status:patient.status}:emptyValues);}},[opened,patient,reset]);
  const submit=handleSubmit(async(values)=>{try{
    if(!patient&&!confirmed){const found=await patientApi.duplicates({nik:optional(values.nik),phone:values.phone,fullName:values.fullName,dateOfBirth:values.dateOfBirth});if(found.length){setDuplicates(found);return;}}
    if(patient){const input:UpdatePatientInput={fullName:values.fullName,nik:optional(values.nik)??null,dateOfBirth:values.dateOfBirth,gender:values.gender,phone:values.phone,email:optional(values.email)??null,address:values.address,bloodType:values.bloodType,status:values.status,emergencyContactName:optional(values.emergencyContactName)??null,emergencyContactPhone:optional(values.emergencyContactPhone)??null,emergencyContactRelationship:optional(values.emergencyContactRelationship)??null,paymentType:values.paymentType,insuranceProvider:optional(values.insuranceProvider)??null,insuranceMemberNumber:optional(values.insuranceMemberNumber)??null};await updatePatient.mutateAsync({id:patient.id,input});}
    else {const input:CreatePatientInput={fullName:values.fullName,nik:optional(values.nik),dateOfBirth:values.dateOfBirth,gender:values.gender,phone:values.phone,email:optional(values.email),address:values.address,bloodType:values.bloodType,emergencyContact:{name:optional(values.emergencyContactName),phone:optional(values.emergencyContactPhone),relationship:optional(values.emergencyContactRelationship)},payment:{type:values.paymentType,insuranceProvider:optional(values.insuranceProvider),insuranceMemberNumber:optional(values.insuranceMemberNumber)},initialMeasurement:{systolicBloodPressure:values.systolicBloodPressure,diastolicBloodPressure:values.diastolicBloodPressure,weightKg:values.weightKg,heightCm:values.heightCm}};await createPatient.mutateAsync(input);}
    notifications.show({color:'teal',title:patient?'Patient updated':'Patient registered',message:patient?'Changes were saved.':'MRN and initial measurement were created together.'});onClose();
  }catch{notifications.show({color:'red',title:'Unable to save patient',message:'Review the information and try again.'});}});
  return <Modal opened={opened} onClose={onClose} title={patient?'Edit patient':'Patient registration'} size="xl" closeOnClickOutside={!isSubmitting}>
    <form onSubmit={submit}><Stack>
      {duplicates.length>0?<Alert color="orange" title="Possible existing patient found"><Stack gap="xs">{duplicates.map(item=><Paper key={item.id} withBorder p="sm"><Group justify="space-between"><div><Text fw={600}>{item.fullName} · {item.mrn}</Text><Text size="sm" c="dimmed">Born {item.dateOfBirth} · {item.phone}</Text></div><Button size="xs" variant="light" onClick={()=>onOpenExisting(item.id)}>Open patient</Button></Group></Paper>)}<Group><Button color="orange" variant="light" onClick={()=>{setConfirmed(true);setDuplicates([]);}}>Create new anyway</Button><Text size="xs" c="dimmed">NIK must still be unique.</Text></Group></Stack></Alert>:null}
      <Paper withBorder p="md" radius="md"><Stack><Title order={4}>Personal information</Title><TextInput label="MRN" value={patient?.mrn??'Generated automatically'} readOnly c="dimmed"/><Grid><Grid.Col span={{base:12,sm:8}}><TextInput label="Full name" required {...register('fullName')} error={errors.fullName?.message}/></Grid.Col><Grid.Col span={{base:12,sm:4}}><TextInput label="NIK / National ID" inputMode="numeric" maxLength={16} {...register('nik')} error={errors.nik?.message}/></Grid.Col><Grid.Col span={{base:12,sm:4}}><Controller name="dateOfBirth" control={control} render={({field})=><DateInput label="Date of birth" required value={field.value?new Date(`${field.value}T00:00:00`):null} onChange={(value)=>field.onChange(value?format(value,'yyyy-MM-dd'):'')} maxDate={new Date()} error={errors.dateOfBirth?.message}/>} /></Grid.Col><Grid.Col span={{base:12,sm:4}}><Controller name="gender" control={control} render={({field})=><Select label="Gender" required data={[{value:'MALE',label:'Male'},{value:'FEMALE',label:'Female'},{value:'OTHER',label:'Other'}]} {...field}/>} /></Grid.Col><Grid.Col span={{base:12,sm:4}}><Controller name="bloodType" control={control} render={({field})=><Select label="Blood type" data={[{value:'A',label:'A'},{value:'B',label:'B'},{value:'AB',label:'AB'},{value:'O',label:'O'},{value:'UNKNOWN',label:'Unknown'}]} {...field}/>} /></Grid.Col></Grid></Stack></Paper>
      <Paper withBorder p="md" radius="md"><Stack><Title order={4}>Contact information</Title><Grid><Grid.Col span={{base:12,sm:6}}><TextInput label="Phone number" required {...register('phone')} error={errors.phone?.message}/></Grid.Col><Grid.Col span={{base:12,sm:6}}><TextInput label="Email" type="email" {...register('email')} error={errors.email?.message}/></Grid.Col><Grid.Col span={12}><Textarea label="Address" required autosize minRows={2} {...register('address')} error={errors.address?.message}/></Grid.Col></Grid></Stack></Paper>
      <Paper withBorder p="md" radius="md"><Stack><Title order={4}>Emergency contact</Title><Grid><Grid.Col span={{base:12,sm:4}}><TextInput label="Name" {...register('emergencyContactName')}/></Grid.Col><Grid.Col span={{base:12,sm:4}}><TextInput label="Phone" {...register('emergencyContactPhone')}/></Grid.Col><Grid.Col span={{base:12,sm:4}}><Controller name="emergencyContactRelationship" control={control} render={({field})=><Select label="Relationship" clearable data={['SPOUSE','PARENT','CHILD','SIBLING','RELATIVE','FRIEND','OTHER']} value={field.value||null} onChange={(value)=>field.onChange(value??'')}/>} /></Grid.Col></Grid></Stack></Paper>
      <Paper withBorder p="md" radius="md"><Stack><Title order={4}>Payment / insurance</Title><Grid><Grid.Col span={{base:12,sm:4}}><Controller name="paymentType" control={control} render={({field})=><Select label="Payment type" data={[{value:'SELF_PAY',label:'Self pay'},{value:'INSURANCE',label:'Insurance'},{value:'COMPANY',label:'Company'},{value:'OTHER',label:'Other'}]} {...field}/>} /></Grid.Col>{paymentType==='INSURANCE'?<><Grid.Col span={{base:12,sm:4}}><TextInput label="Insurance provider" {...register('insuranceProvider')}/></Grid.Col><Grid.Col span={{base:12,sm:4}}><TextInput label="Member number" {...register('insuranceMemberNumber')}/></Grid.Col></>:null}</Grid></Stack></Paper>
      {!patient?<Paper withBorder p="md" radius="md" bg="teal.0"><Stack><div><Title order={4}>Initial measurement</Title><Text size="sm" c="dimmed">Stored as the first measurement-history record, not in the patient profile.</Text></div><Grid><Grid.Col span={{base:12,sm:6}}><Text fw={500} size="sm">Blood pressure</Text><Group grow align="flex-start"><Controller name="systolicBloodPressure" control={control} render={({field})=><NumberInput label="Systolic" suffix=" mmHg" min={40} max={300} value={field.value} onChange={field.onChange} error={errors.systolicBloodPressure?.message}/>} /><Controller name="diastolicBloodPressure" control={control} render={({field})=><NumberInput label="Diastolic" suffix=" mmHg" min={20} max={200} value={field.value} onChange={field.onChange} error={errors.diastolicBloodPressure?.message}/>} /></Group></Grid.Col><Grid.Col span={{base:12,sm:3}}><Controller name="weightKg" control={control} render={({field})=><NumberInput label="Weight" suffix=" kg" decimalScale={1} min={0.1} value={field.value} onChange={field.onChange} error={errors.weightKg?.message}/>} /></Grid.Col><Grid.Col span={{base:12,sm:3}}><Controller name="heightCm" control={control} render={({field})=><NumberInput label="Height" suffix=" cm" decimalScale={1} min={1} value={field.value} onChange={field.onChange} error={errors.heightCm?.message}/>} /></Grid.Col></Grid></Stack></Paper>:<><Divider/><Controller name="status" control={control} render={({field})=><Select label="Active status" data={['ACTIVE','INACTIVE']} {...field} maw={240}/>} /></>}
      <Group justify="flex-end"><Button variant="default" onClick={onClose} disabled={isSubmitting}>Cancel</Button><Button type="submit" loading={isSubmitting}>{patient?'Save changes':'Register patient'}</Button></Group>
    </Stack></form>
  </Modal>;
}
