import { Alert, Badge, Button, Card, Center, Drawer, Group, Loader, Pagination, SimpleGrid, Stack, Table, Text, Title } from '@mantine/core';
import { useDisclosure } from '@mantine/hooks';
import { format } from 'date-fns';
import { useState } from 'react';
import { useMeasurements, usePatient } from '../api/patient-queries';
import { MeasurementModal } from './MeasurementModal';

type Props={patientId:string|null;onClose:()=>void};
const age=(date:string)=>{const now=new Date();const birth=new Date(`${date}T00:00:00`);let years=now.getFullYear()-birth.getFullYear();if(now<new Date(now.getFullYear(),birth.getMonth(),birth.getDate()))years--;return years;};
export function PatientDetailDrawer({patientId,onClose}:Props){const[page,setPage]=useState(1);const[opened,{open,close}]=useDisclosure();const patient=usePatient(patientId??'');const history=useMeasurements(patientId??'',page);const value=patient.data;const latest=value?.latestMeasurement;return <Drawer opened={Boolean(patientId)} onClose={onClose} title="Patient detail" position="right" size="xl">{patient.isLoading?<Center py={60}><Loader/></Center>:patient.isError||!value?<Alert color="red">Unable to load patient.</Alert>:<Stack><div><Group justify="space-between"><div><Title order={3}>{value.fullName}</Title><Text c="dimmed">{value.mrn} · {age(value.dateOfBirth)} years · {value.gender} · {value.phone}</Text></div><Badge color={value.status==='ACTIVE'?'teal':'gray'}>{value.status}</Badge></Group></div><SimpleGrid cols={{base:1,sm:4}}>{[{label:'Latest blood pressure',value:latest?`${latest.systolicBloodPressure}/${latest.diastolicBloodPressure} mmHg`:'—'},{label:'Latest weight',value:latest?`${latest.weightKg} kg`:'—'},{label:'Latest height',value:latest?`${latest.heightCm} cm`:'—'},{label:'Last measured',value:latest?format(new Date(latest.measuredAt),'dd MMM yyyy HH:mm'):'—'}].map(item=><Card key={item.label} withBorder><Text size="xs" c="dimmed">{item.label}</Text><Text fw={700}>{item.value}</Text></Card>)}</SimpleGrid><Group justify="space-between"><Title order={4}>Measurement history</Title><Button size="sm" onClick={open}>Add measurement</Button></Group>{history.isLoading?<Center py={30}><Loader size="sm"/></Center>:history.isError?<Alert color="red">Unable to load measurement history.</Alert>:history.data!.data.length===0?<Text c="dimmed">No measurements recorded.</Text>:<><Table.ScrollContainer minWidth={620}><Table withTableBorder striped><Table.Thead><Table.Tr><Table.Th>Date</Table.Th><Table.Th>Blood pressure</Table.Th><Table.Th>Weight</Table.Th><Table.Th>Height</Table.Th><Table.Th>Visit</Table.Th></Table.Tr></Table.Thead><Table.Tbody>{history.data!.data.map(item=><Table.Tr key={item.id}><Table.Td>{format(new Date(item.measuredAt),'dd MMM yyyy HH:mm')}</Table.Td><Table.Td>{item.systolicBloodPressure}/{item.diastolicBloodPressure} mmHg</Table.Td><Table.Td>{item.weightKg} kg</Table.Td><Table.Td>{item.heightCm} cm</Table.Td><Table.Td>{item.visitId?item.visitId.slice(0,8):'Initial registration'}</Table.Td></Table.Tr>)}</Table.Tbody></Table></Table.ScrollContainer><Pagination value={page} onChange={setPage} total={Math.max(1,history.data!.meta.totalPages)}/></>}<MeasurementModal patientId={value.id} opened={opened} onClose={close}/></Stack>}</Drawer>}
