import { sql } from 'drizzle-orm';
import { boolean, check, date, index, integer, numeric, pgEnum, pgTable, primaryKey, text, timestamp, uniqueIndex, uuid } from 'drizzle-orm/pg-core';

export const visitStatus = pgEnum('visit_status', ['IN_PROGRESS', 'COMPLETED', 'CANCELLED']);
export const visits = pgTable('visits', {
  id: uuid('id').primaryKey().defaultRandom(), appointmentId: uuid('appointment_id').unique(), queueEntryId: uuid('queue_entry_id').unique(), patientId: uuid('patient_id').notNull(), doctorId: uuid('doctor_id').notNull(), status: visitStatus('status').notNull().default('IN_PROGRESS'),
  chiefComplaint: text('chief_complaint'), historyOfPresentIllness: text('history_of_present_illness'), physicalExamination: text('physical_examination'), clinicalFindings: text('clinical_findings'), treatmentPlan: text('treatment_plan'), followUp: text('follow_up'), additionalNotes: text('additional_notes'),
  examinationFindings: text('examination_findings'), clinicalNote: text('clinical_note'), treatmentNote: text('treatment_note'), followUpNote: text('follow_up_note'), followUpDate: date('follow_up_date', { mode: 'string' }),
  startedAt: timestamp('started_at', { withTimezone: true }).notNull().defaultNow(), completedAt: timestamp('completed_at', { withTimezone: true }), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [index('visits_patient_idx').on(table.patientId), index('visits_doctor_idx').on(table.doctorId), index('visits_started_idx').on(table.startedAt)]);

export const vitalSigns = pgTable('vital_signs', { id: uuid('id').primaryKey().defaultRandom(), visitId: uuid('visit_id').notNull().unique(), systolic: integer('systolic'), diastolic: integer('diastolic'), heartRate: integer('heart_rate'), respiratoryRate: integer('respiratory_rate'), temperature: numeric('temperature', { precision: 4, scale: 1 }), spo2: integer('spo2'), weight: numeric('weight', { precision: 5, scale: 2 }), height: numeric('height', { precision: 5, scale: 2 }), recordedBy: uuid('recorded_by').notNull(), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow() }, (table) => [check('vital_systolic_check', sql`${table.systolic} BETWEEN 40 AND 300`), check('vital_diastolic_check', sql`${table.diastolic} BETWEEN 20 AND 200`), check('vital_spo2_check', sql`${table.spo2} BETWEEN 0 AND 100`)]);
export const diagnoses = pgTable('diagnoses', { id: uuid('id').primaryKey().defaultRandom(), icd10Code: text('icd10_code').notNull().unique(), name: text('name').notNull(), description: text('description'), isActive: boolean('is_active').notNull().default(true), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow() }, (table) => [index('diagnoses_name_idx').on(table.name)]);
export const visitDiagnoses = pgTable('visit_diagnoses', { visitId: uuid('visit_id').notNull(), diagnosisId: uuid('diagnosis_id').notNull(), isPrimary: boolean('is_primary').notNull().default(false), notes: text('notes'), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow() }, (table) => [primaryKey({ columns: [table.visitId, table.diagnosisId] }), uniqueIndex('visit_diagnoses_primary_uidx').on(table.visitId).where(sql`${table.isPrimary}=true`), index('visit_diagnoses_visit_idx').on(table.visitId)]);
