import { sql } from 'drizzle-orm';
import { boolean, check, date, index, integer, numeric, pgEnum, pgTable, primaryKey, text, time, timestamp, uniqueIndex, uuid } from 'drizzle-orm/pg-core';

export const appointmentStatus = pgEnum('appointment_status', ['BOOKED','CONFIRMED','CHECKED_IN','IN_PROGRESS','COMPLETED','CANCELLED','NO_SHOW']);
export const queueStatus = pgEnum('queue_status', ['WAITING','CALLED','IN_CONSULTATION','COMPLETED','SKIPPED','CANCELLED']);

export const doctors = pgTable('doctors', {
  id: uuid('id').primaryKey().defaultRandom(), userId: uuid('user_id').notNull().unique(), specialty: text('specialty').notNull(), licenseNumber: text('license_number').notNull().unique(), isActive: boolean('is_active').notNull().default(true), createdAt: timestamp('created_at',{withTimezone:true}).notNull().defaultNow(), updatedAt: timestamp('updated_at',{withTimezone:true}).notNull().defaultNow(),
});
export const doctorSchedules = pgTable('doctor_schedules', {
  id: uuid('id').primaryKey().defaultRandom(), doctorId: uuid('doctor_id').notNull(), dayOfWeek: integer('day_of_week').notNull(), startTime: time('start_time').notNull(), endTime: time('end_time').notNull(), breakStart: time('break_start'), breakEnd: time('break_end'), slotDurationMinutes: integer('slot_duration_minutes').notNull().default(20), maximumPatients: integer('maximum_patients').notNull().default(12), isActive: boolean('is_active').notNull().default(true), createdAt: timestamp('created_at',{withTimezone:true}).notNull().defaultNow(), updatedAt: timestamp('updated_at',{withTimezone:true}).notNull().defaultNow(),
},(table)=>[check('doctor_schedules_day_check',sql`${table.dayOfWeek} BETWEEN 0 AND 6`),check('doctor_schedules_time_check',sql`${table.endTime} > ${table.startTime}`),check('doctor_schedules_slot_check',sql`${table.slotDurationMinutes} > 0`),uniqueIndex('doctor_schedules_slot_uidx').on(table.doctorId,table.dayOfWeek,table.startTime),index('doctor_schedules_doctor_idx').on(table.doctorId)]);
export const clinicServices = pgTable('services', {
  id: uuid('id').primaryKey().defaultRandom(), code: text('code').notNull().unique(), name: text('name').notNull().unique(), description: text('description'), durationMinutes: integer('duration_minutes').notNull().default(20), price: numeric('price',{precision:14,scale:2}).notNull(), isActive: boolean('is_active').notNull().default(true), createdAt: timestamp('created_at',{withTimezone:true}).notNull().defaultNow(), updatedAt: timestamp('updated_at',{withTimezone:true}).notNull().defaultNow(),
},(table)=>[check('services_duration_check',sql`${table.durationMinutes}>0`),check('services_price_check',sql`${table.price}>=0`)]);
export const appointments = pgTable('appointments', {
  id: uuid('id').primaryKey().defaultRandom(), patientId: uuid('patient_id').notNull(), doctorId: uuid('doctor_id').notNull(), serviceId: uuid('service_id').notNull(), appointmentDate: date('appointment_date',{mode:'string'}).notNull(), startTime: time('start_time').notNull(), endTime: time('end_time').notNull(), status: appointmentStatus('status').notNull().default('BOOKED'), notes: text('notes'), createdBy: uuid('created_by').notNull(), createdAt: timestamp('created_at',{withTimezone:true}).notNull().defaultNow(), updatedAt: timestamp('updated_at',{withTimezone:true}).notNull().defaultNow(),
},(table)=>[check('appointments_time_check',sql`${table.endTime}>${table.startTime}`),uniqueIndex('appointments_doctor_start_uidx').on(table.doctorId,table.appointmentDate,table.startTime).where(sql`${table.status} NOT IN ('CANCELLED','NO_SHOW')`),index('appointments_date_idx').on(table.appointmentDate),index('appointments_patient_idx').on(table.patientId),index('appointments_doctor_idx').on(table.doctorId),index('appointments_status_idx').on(table.status)]);
export const queueCounters = pgTable('queue_counters', { queueDate: date('queue_date',{mode:'string'}).notNull(), prefix:text('prefix').notNull(), nextValue:integer('next_value').notNull().default(1) },(table)=>[primaryKey({columns:[table.queueDate,table.prefix]}),check('queue_counters_positive_check',sql`${table.nextValue}>0`)]);
export const queueEntries = pgTable('queue_entries', {
  id: uuid('id').primaryKey().defaultRandom(), appointmentId: uuid('appointment_id').notNull().unique(), patientId: uuid('patient_id').notNull(), doctorId: uuid('doctor_id').notNull(), queueDate: date('queue_date',{mode:'string'}).notNull(), queueNumber:text('queue_number').notNull(), status:queueStatus('status').notNull().default('WAITING'), checkedInAt:timestamp('checked_in_at',{withTimezone:true}).notNull().defaultNow(), calledAt:timestamp('called_at',{withTimezone:true}), completedAt:timestamp('completed_at',{withTimezone:true}), createdAt:timestamp('created_at',{withTimezone:true}).notNull().defaultNow(), updatedAt:timestamp('updated_at',{withTimezone:true}).notNull().defaultNow(),
},(table)=>[uniqueIndex('queue_entries_number_uidx').on(table.queueDate,table.queueNumber),index('queue_entries_doctor_date_idx').on(table.doctorId,table.queueDate),index('queue_entries_status_idx').on(table.status)]);
