import{useMutation,useQuery,useQueryClient}from'@tanstack/react-query';import{api}from'../../app/api/client';
export type Diagnosis={id:string;icd10Code:string;name:string};
export type VisitMeasurement={id:string;systolicBloodPressure:number;diastolicBloodPressure:number;weightKg:string;heightCm:string;temperature:string|null;heartRate:number|null;respiratoryRate:number|null;oxygenSaturation:number|null;measuredAt:string;visitId:string|null};
export type VisitDetail={id:string;status:string;patientId:string;patientName:string;mrn:string;dateOfBirth:string;gender:string;phone:string;bloodType:string|null;allergies:string|null;doctorName:string;chiefComplaint:string|null;examinationFindings:string|null;clinicalNote:string|null;treatmentNote:string|null;followUpNote:string|null;followUpDate:string|null;vitalSigns:VisitMeasurement|null;vitalSignsForCurrentVisit:boolean;measurementHistory:VisitMeasurement[];diagnoses:Array<Diagnosis&{diagnosisId:string;isPrimary:boolean;notes:string|null}>;previousVisits:Array<{id:string;startedAt:string;chiefComplaint:string|null;examinationFindings:string|null;status:string;doctorName:string;diagnoses:Array<{icd10Code:string;name:string;isPrimary:boolean}>;medicines:Array<{name:string;dosage:string}>}>};
const unwrap=<T>(response:{data:{data:T}})=>response.data.data;
export const useVisit=(id:string)=>useQuery({queryKey:['visit',id],queryFn:async()=>unwrap<VisitDetail>(await api.get(`/visits/${id}`))});
const useVisitMutation=(path:(id:string)=>string,method:'patch'|'put'|'post')=>{const client=useQueryClient();return useMutation({mutationFn:async({id,data}:{id:string;data?:unknown})=>unwrap(await api[method](path(id),data)),onSuccess:(_data,input)=>client.invalidateQueries({queryKey:['visit',input.id]})});};
export const useConsultationDraft=()=>useVisitMutation((id)=>`/visits/${id}/consultation`,'patch');export const useVitals=()=>useVisitMutation((id)=>`/visits/${id}/vitals`,'put');export const useAddDiagnosis=()=>useVisitMutation((id)=>`/visits/${id}/diagnoses`,'post');export const useCompleteVisit=()=>useVisitMutation((id)=>`/visits/${id}/complete`,'post');
export const useDiagnoses=(search:string)=>useQuery({queryKey:['diagnoses',search],queryFn:async()=>unwrap<Diagnosis[]>(await api.get('/diagnoses',{params:{search}})),staleTime:60_000});
