import { useEffect } from 'react';
import { zodResolver } from '@hookform/resolvers/zod';
import { Alert, Button, Center, Grid, Group, Loader, Modal, NumberInput, Paper, SimpleGrid, Stack, Text, Textarea, Title } from '@mantine/core';
import { DateInput } from '@mantine/dates';
import { useDisclosure } from '@mantine/hooks';
import { notifications } from '@mantine/notifications';
import { Controller, useForm } from 'react-hook-form';
import { format } from 'date-fns';
import { useNavigate, useParams } from 'react-router-dom';
import { z } from 'zod';
import { PrescriptionSection } from '../prescriptions/PrescriptionSection';
import { useCompleteVisit, useConsultationDraft, useVisit, useVitals } from './api';
import { DiagnosisSection } from './components/DiagnosisSection';
import { PatientHistoryDrawer } from './components/PatientHistoryDrawer';
import { PatientSummary } from './components/PatientSummary';

const consultationSchema=z.object({chiefComplaint:z.string().max(2000),examinationFindings:z.string().max(5000),clinicalNote:z.string().max(5000),treatmentNote:z.string().max(5000),followUpNote:z.string().max(2000),followUpDate:z.string()});
type ConsultationValues=z.infer<typeof consultationSchema>;
type VitalValues={systolic:number|string;diastolic:number|string;weight:number|string;height:number|string;temperature:number|string;heartRate:number|string;respiratoryRate:number|string;spo2:number|string};
const blankConsultation:ConsultationValues={chiefComplaint:'',examinationFindings:'',clinicalNote:'',treatmentNote:'',followUpNote:'',followUpDate:''};
const blankVitals:VitalValues={systolic:'',diastolic:'',weight:'',height:'',temperature:'',heartRate:'',respiratoryRate:'',spo2:''};

export function ConsultationPage(){const{id=''}=useParams();const navigate=useNavigate();const visit=useVisit(id);const draft=useConsultationDraft();const vitalMutation=useVitals();const complete=useCompleteVisit();const[historyOpened,history]=useDisclosure();const[completeOpened,completeModal]=useDisclosure();const form=useForm<ConsultationValues>({resolver:zodResolver(consultationSchema),defaultValues:blankConsultation});const vitals=useForm<VitalValues>({defaultValues:blankVitals});
  useEffect(()=>{if(!visit.data)return;form.reset({chiefComplaint:visit.data.chiefComplaint??'',examinationFindings:visit.data.examinationFindings??'',clinicalNote:visit.data.clinicalNote??'',treatmentNote:visit.data.treatmentNote??'',followUpNote:visit.data.followUpNote??'',followUpDate:visit.data.followUpDate??''});const record=visit.data.vitalSigns;vitals.reset(record?{systolic:record.systolicBloodPressure,diastolic:record.diastolicBloodPressure,weight:Number(record.weightKg),height:Number(record.heightCm),temperature:record.temperature?Number(record.temperature):'',heartRate:record.heartRate??'',respiratoryRate:record.respiratoryRate??'',spo2:record.oxygenSaturation??''}:blankVitals);},[visit.data,form,vitals]);
  if(visit.isLoading)return <Center py={80}><Loader/></Center>;if(visit.isError||!visit.data)return <Alert color="red">Unable to load consultation.</Alert>;const data=visit.data;
  const persist=async(showNotification:boolean)=>{const values=form.getValues();const vitalValues=vitals.getValues();const core=[vitalValues.systolic,vitalValues.diastolic,vitalValues.weight,vitalValues.height];const anyVital=Object.values(vitalValues).some(value=>value!=='');if(anyVital&&core.some(value=>value==='')){notifications.show({color:'red',message:'Blood pressure, weight, and height are required when saving measurements.'});return false;}try{const operations:Promise<unknown>[]=[draft.mutateAsync({id,data:{...values,followUpDate:values.followUpDate||undefined}})];if(anyVital)operations.push(vitalMutation.mutateAsync({id,data:Object.fromEntries(Object.entries(vitalValues).filter(([,value])=>value!=='').map(([key,value])=>[key,Number(value)]))}));await Promise.all(operations);if(showNotification)notifications.show({color:'teal',message:'Consultation draft saved'});return true;}catch{notifications.show({color:'red',message:'Unable to save consultation draft'});return false;}};
  const finish=async()=>{const values=form.getValues();if(!values.chiefComplaint.trim()){form.setError('chiefComplaint',{message:'Chief complaint is required'});completeModal.close();return;}if(!data.diagnoses.some(item=>item.isPrimary)){notifications.show({color:'red',message:'Add one primary diagnosis before completing.'});completeModal.close();return;}if(!await persist(false))return;try{await complete.mutateAsync({id});notifications.show({color:'teal',title:'Consultation completed',message:'Queue completed and any draft prescription was sent to pharmacy.'});navigate('/doctor/dashboard');}catch{notifications.show({color:'red',title:'Cannot complete',message:'Chief complaint and a primary diagnosis are required.'});}finally{completeModal.close();}};
  const busy=draft.isPending||vitalMutation.isPending||complete.isPending;
  return <Stack gap="md"><Group justify="space-between" align="flex-start"><div><Title order={2}>Consultation</Title><Text c="dimmed">{data.doctorName} · one-page outpatient record</Text></div><Group><Button variant="default" onClick={history.open}>Patient history</Button><Button variant="light" onClick={()=>void persist(true)} loading={draft.isPending||vitalMutation.isPending}>Save draft</Button><Button color="teal" onClick={completeModal.open}>Complete consultation</Button></Group></Group><PatientSummary visit={data}/>
    <form onSubmit={form.handleSubmit(()=>persist(true))}><Stack gap="md"><Paper withBorder p="md" radius="lg"><Stack><div><Text fw={700}>Complaint</Text><Text size="sm" c="dimmed">The main reason for today’s visit.</Text></div><Textarea label="Chief complaint" required autosize minRows={2} placeholder="Fever and cough for 2 days" {...form.register('chiefComplaint')} error={form.formState.errors.chiefComplaint?.message}/></Stack></Paper>
      <Paper withBorder p="md" radius="lg"><Stack><div><Text fw={700}>Vital signs</Text><Text size="sm" c="dimmed">Check-in measurements are pre-filled. Only change them when needed.</Text></div><SimpleGrid cols={{base:2,sm:4}}>{([['systolic','Systolic',' mmHg'],['diastolic','Diastolic',' mmHg'],['weight','Weight',' kg'],['height','Height',' cm'],['temperature','Temperature',' °C'],['heartRate','Pulse',' bpm'],['respiratoryRate','Respiratory rate',' /min'],['spo2','SpO₂','%']] as const).map(([name,label,suffix])=><Controller key={name} name={name} control={vitals.control} render={({field})=><NumberInput label={label} suffix={suffix} decimalScale={name==='temperature'||name==='weight'||name==='height'?1:0} value={field.value} onChange={field.onChange}/>} />)}</SimpleGrid></Stack></Paper>
      <Paper withBorder p="md" radius="lg"><Stack><div><Text fw={700}>Examination / findings</Text><Text size="sm" c="dimmed">Keep this concise; no long structured examination is required.</Text></div><Textarea label="Examination findings" autosize minRows={3} placeholder="Throat mildly red, lungs clear, no shortness of breath" {...form.register('examinationFindings')}/></Stack></Paper>
      <DiagnosisSection visit={data}/>
      <Paper withBorder p="md" radius="lg"><PrescriptionSection visitId={id}/></Paper>
      <Paper withBorder p="md" radius="lg"><Stack><Text fw={700}>Treatment / notes</Text><Grid><Grid.Col span={{base:12,sm:6}}><Textarea label="Treatment without medicine" description="Optional procedure or non-medication treatment" autosize minRows={2} {...form.register('treatmentNote')}/></Grid.Col><Grid.Col span={{base:12,sm:6}}><Textarea label="Clinical note" description="Optional additional clinical information" autosize minRows={2} {...form.register('clinicalNote')}/></Grid.Col></Grid></Stack></Paper>
      <Paper withBorder p="md" radius="lg"><Stack><Text fw={700}>Advice / follow-up</Text><Grid><Grid.Col span={{base:12,sm:8}}><Textarea label="Advice / follow-up" autosize minRows={2} placeholder="Rest, hydration, return if symptoms worsen" {...form.register('followUpNote')}/></Grid.Col><Grid.Col span={{base:12,sm:4}}><Controller name="followUpDate" control={form.control} render={({field})=><DateInput clearable label="Follow-up date" value={field.value?new Date(`${field.value}T00:00:00`):null} onChange={value=>field.onChange(value?format(value,'yyyy-MM-dd'):'')} minDate={new Date()}/>} /></Grid.Col></Grid></Stack></Paper>
      <Group justify="flex-end" pb="xl"><Button variant="default" onClick={()=>navigate('/doctor/dashboard')}>Back to queue</Button><Button type="submit" variant="light" loading={draft.isPending||vitalMutation.isPending}>Save draft</Button><Button color="teal" onClick={completeModal.open}>Complete consultation</Button></Group></Stack></form>
    <PatientHistoryDrawer opened={historyOpened} onClose={history.close} visit={data}/><Modal opened={completeOpened} onClose={completeModal.close} title="Complete consultation?" centered><Stack><Text>This finalizes the visit and queue. A draft prescription containing medicine will be submitted automatically to Pharmacy.</Text><Group justify="flex-end"><Button variant="default" onClick={completeModal.close}>Continue editing</Button><Button color="teal" onClick={()=>void finish()} loading={busy}>Complete consultation</Button></Group></Stack></Modal>
  </Stack>;
}
