import { zodResolver } from '@hookform/resolvers/zod';
import { Alert, Badge, Button, Center, Divider, Group, Loader, Modal, NumberInput, Pagination, Paper, Select, Stack, Table, Text, TextInput, Title } from '@mantine/core';
import { useDebouncedValue, useDisclosure } from '@mantine/hooks';
import { notifications } from '@mantine/notifications';
import { IconAlertCircle, IconCash, IconFileInvoice } from '@tabler/icons-react';
import { Controller, useForm } from 'react-hook-form';
import { useState } from 'react';
import { z } from 'zod';
import { useCreatePayment, useGenerateInvoice, useInvoice, useInvoices, useUnbilledVisits } from './api';

const money = new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 });
const invoiceSchema = z.object({ visitId: z.string().uuid(), discount: z.number().min(0), tax: z.number().min(0) });
const paymentSchema = z.object({ amount: z.number().positive(), method: z.enum(['CASH', 'DEBIT_CARD', 'CREDIT_CARD', 'BANK_TRANSFER', 'QRIS', 'INSURANCE']), reference: z.string().max(200).optional() });
type InvoiceForm = z.infer<typeof invoiceSchema>;
type PaymentForm = z.infer<typeof paymentSchema>;

export function BillingPage() {
  const [page, setPage] = useState(1); const [search, setSearch] = useState(''); const [debounced] = useDebouncedValue(search, 300); const [selected, setSelected] = useState<string | null>(null);
  const [generateOpened, generateModal] = useDisclosure(); const [detailOpened, detailModal] = useDisclosure(); const [paymentOpened, paymentModal] = useDisclosure();
  const invoices = useInvoices(page, debounced); const visits = useUnbilledVisits(); const detail = useInvoice(selected); const generate = useGenerateInvoice(); const pay = useCreatePayment();
  const invoiceForm = useForm<InvoiceForm>({ resolver: zodResolver(invoiceSchema), defaultValues: { visitId: '', discount: 0, tax: 0 } });
  const paymentForm = useForm<PaymentForm>({ resolver: zodResolver(paymentSchema), defaultValues: { amount: 0, method: 'CASH', reference: '' } });
  const openDetail = (id: string) => { setSelected(id); detailModal.open(); };
  const createInvoice = invoiceForm.handleSubmit(async (values) => { try { const created = await generate.mutateAsync(values); generateModal.close(); invoiceForm.reset(); openDetail(created.id); notifications.show({ color: 'teal', title: created.invoiceNumber, message: 'Invoice created from server-side service and medicine prices.' }); } catch { notifications.show({ color: 'red', title: 'Invoice failed', message: 'The visit must be complete and its prescription dispensed.' }); } });
  const createPayment = paymentForm.handleSubmit(async (values) => { if (!selected) return; try { await pay.mutateAsync({ invoiceId: selected, ...values, reference: values.reference || undefined }); paymentModal.close(); paymentForm.reset(); await detail.refetch(); notifications.show({ color: 'teal', title: 'Payment received', message: 'Invoice balance and status were updated.' }); } catch { notifications.show({ color: 'red', title: 'Payment failed', message: 'Payment cannot exceed the outstanding balance.' }); } });
  return <Stack><Group justify="space-between"><div><Title order={2}>Billing</Title><Text c="dimmed">Create visit invoices, receive payments, and review receipts.</Text></div><Button leftSection={<IconFileInvoice size={18}/>} onClick={generateModal.open}>Create invoice</Button></Group><Paper withBorder p="md" radius="lg"><Stack><TextInput placeholder="Search invoice, patient, or MRN" value={search} onChange={(event) => { setSearch(event.currentTarget.value); setPage(1); }}/>{invoices.isLoading ? <Center py={50}><Loader/></Center> : invoices.isError ? <Alert color="red" icon={<IconAlertCircle/>}>Unable to load invoices.</Alert> : invoices.data!.data.length === 0 ? <Center py={50}><Text c="dimmed">No invoices found.</Text></Center> : <><Table.ScrollContainer minWidth={760}><Table striped highlightOnHover><Table.Thead><Table.Tr><Table.Th>Invoice</Table.Th><Table.Th>Patient</Table.Th><Table.Th>Date</Table.Th><Table.Th>Total</Table.Th><Table.Th>Paid</Table.Th><Table.Th>Status</Table.Th><Table.Th/></Table.Tr></Table.Thead><Table.Tbody>{invoices.data!.data.map((item) => <Table.Tr key={item.id}><Table.Td>{item.invoiceNumber}</Table.Td><Table.Td><Text fw={500}>{item.patientName}</Text><Text size="xs" c="dimmed">{item.mrn}</Text></Table.Td><Table.Td>{item.invoiceDate}</Table.Td><Table.Td>{money.format(Number(item.grandTotal))}</Table.Td><Table.Td>{money.format(Number(item.amountPaid))}</Table.Td><Table.Td><Badge color={item.status === 'PAID' ? 'teal' : item.status === 'PARTIAL' ? 'orange' : 'gray'}>{item.status}</Badge></Table.Td><Table.Td><Button size="xs" variant="light" onClick={() => openDetail(item.id)}>Open</Button></Table.Td></Table.Tr>)}</Table.Tbody></Table></Table.ScrollContainer><Group justify="space-between"><Text size="sm" c="dimmed">{invoices.data!.meta.total} invoices</Text><Pagination value={page} onChange={setPage} total={Math.max(1, invoices.data!.meta.totalPages)}/></Group></>}</Stack></Paper>
  <Modal opened={generateOpened} onClose={generateModal.close} title="Create visit invoice"><form onSubmit={createInvoice}><Stack><Controller control={invoiceForm.control} name="visitId" render={({ field, fieldState }) => <Select searchable label="Completed visit" data={(visits.data ?? []).map((visit) => ({ value: visit.id, label: `${visit.mrn} - ${visit.patientName} - ${visit.serviceName ?? 'Visit'}` }))} {...field} error={fieldState.error?.message} nothingFoundMessage="No unbilled visits"/>}/><Controller control={invoiceForm.control} name="discount" render={({ field }) => <NumberInput label="Discount" min={0} decimalScale={2} {...field}/>}/><Controller control={invoiceForm.control} name="tax" render={({ field }) => <NumberInput label="Tax" min={0} decimalScale={2} {...field}/>}/><Group justify="flex-end"><Button variant="default" onClick={generateModal.close}>Cancel</Button><Button type="submit" loading={generate.isPending}>Generate</Button></Group></Stack></form></Modal>
  <Modal opened={detailOpened} onClose={detailModal.close} title="Invoice receipt" size="lg">{detail.isLoading ? <Center><Loader/></Center> : detail.data ? <Stack><Group justify="space-between"><div><Text fw={700}>{detail.data.invoiceNumber}</Text><Text>{detail.data.patientName} · {detail.data.mrn}</Text></div><Badge>{detail.data.status}</Badge></Group><Divider/><Table><Table.Thead><Table.Tr><Table.Th>Description</Table.Th><Table.Th>Qty</Table.Th><Table.Th>Price</Table.Th><Table.Th>Total</Table.Th></Table.Tr></Table.Thead><Table.Tbody>{detail.data.items.map((item) => <Table.Tr key={item.id}><Table.Td>{item.description}<Text size="xs" c="dimmed">{item.type}</Text></Table.Td><Table.Td>{item.quantity}</Table.Td><Table.Td>{money.format(Number(item.unitPrice))}</Table.Td><Table.Td>{money.format(Number(item.total))}</Table.Td></Table.Tr>)}</Table.Tbody></Table><Stack gap={2} align="flex-end"><Text>Subtotal: {money.format(Number(detail.data.subtotal))}</Text><Text>Discount: {money.format(Number(detail.data.discount))}</Text><Text>Tax: {money.format(Number(detail.data.tax))}</Text><Text fw={700}>Grand total: {money.format(Number(detail.data.grandTotal))}</Text><Text c={Number(detail.data.balance) > 0 ? 'orange' : 'teal'} fw={700}>Balance: {money.format(Number(detail.data.balance))}</Text></Stack>{Number(detail.data.balance) > 0 ? <Group justify="flex-end"><Button leftSection={<IconCash size={18}/>} onClick={() => { paymentForm.setValue('amount', Number(detail.data!.balance)); paymentModal.open(); }}>Receive payment</Button></Group> : null}</Stack> : null}</Modal>
  <Modal opened={paymentOpened} onClose={paymentModal.close} title="Receive payment"><form onSubmit={createPayment}><Stack><Controller control={paymentForm.control} name="amount" render={({ field, fieldState }) => <NumberInput label="Amount" min={0.01} decimalScale={2} {...field} error={fieldState.error?.message}/>}/><Controller control={paymentForm.control} name="method" render={({ field, fieldState }) => <Select label="Method" data={['CASH', 'DEBIT_CARD', 'CREDIT_CARD', 'BANK_TRANSFER', 'QRIS', 'INSURANCE']} {...field} error={fieldState.error?.message}/>}/><TextInput label="Reference (optional)" {...paymentForm.register('reference')}/><Group justify="flex-end"><Button variant="default" onClick={paymentModal.close}>Cancel</Button><Button type="submit" loading={pay.isPending}>Confirm payment</Button></Group></Stack></form></Modal></Stack>;
}
