import { useEffect, useState } from 'react';
import { Alert, Button, Center, Group, Loader, Pagination, Paper, Stack, Text, TextInput, Title } from '@mantine/core';
import { useDisclosure } from '@mantine/hooks';
import { IconAlertCircle, IconPlus, IconSearch, IconUsers } from '@tabler/icons-react';
import { usePatients } from './api/patient-queries';
import { PatientDetailDrawer } from './components/PatientDetailDrawer';
import { PatientFormModal } from './components/PatientFormModal';
import { PatientsTable } from './components/PatientsTable';
import type { Patient } from './types';

export function PatientsPage(){const[page,setPage]=useState(1);const[search,setSearch]=useState('');const[debounced,setDebounced]=useState('');const[selected,setSelected]=useState<Patient|null>(null);const[detailId,setDetailId]=useState<string|null>(null);const[opened,{open,close}]=useDisclosure();useEffect(()=>{const timer=window.setTimeout(()=>{setDebounced(search);setPage(1);},350);return()=>window.clearTimeout(timer);},[search]);const query=usePatients({page,limit:20,search:debounced,sortBy:'createdAt',sortDirection:'desc'});const startCreate=()=>{setSelected(null);open();};const startEdit=(patient:Patient)=>{setSelected(patient);open();};const openExisting=(id:string)=>{close();setDetailId(id);};return <Stack><Group justify="space-between" align="flex-start"><div><Title order={2}>Patients</Title><Text c="dimmed">Register patients and maintain measurement history separately from demographics.</Text></div><Button leftSection={<IconPlus size={18}/>} onClick={startCreate}>Register patient</Button></Group><Paper withBorder radius="lg"><Stack p="md"><TextInput aria-label="Search patients" placeholder="Search MRN, name, NIK, or phone" leftSection={<IconSearch size={18}/>} value={search} onChange={(event)=>setSearch(event.currentTarget.value)}/>{query.isLoading?<Center py={60}><Loader/></Center>:query.isError?<Alert color="red" icon={<IconAlertCircle/>} title="Unable to load patients">Check the connection and try again.</Alert>:query.data!.data.length===0?<Center py={60}><Stack align="center" gap="xs"><IconUsers size={36} color="var(--mantine-color-gray-5)"/><Text fw={600}>No patients found</Text><Text c="dimmed" size="sm">{debounced?'Try another search.':'Register the first patient to get started.'}</Text></Stack></Center>:<><PatientsTable patients={query.data!.data} onEdit={startEdit} onView={(patient)=>setDetailId(patient.id)}/><Group justify="space-between"><Text size="sm" c="dimmed">{query.data!.meta.total} patients</Text><Pagination value={page} onChange={setPage} total={Math.max(query.data!.meta.totalPages,1)}/></Group></>}</Stack></Paper><PatientFormModal opened={opened} onClose={close} patient={selected} onOpenExisting={openExisting}/><PatientDetailDrawer patientId={detailId} onClose={()=>setDetailId(null)}/></Stack>}
