import { Alert, Button, Center, Group, Loader, Paper, Select, Stack, Table, Text, TextInput, Title } from '@mantine/core';
import { notifications } from '@mantine/notifications';
import { IconDownload } from '@tabler/icons-react';
import { useState } from 'react';
import { downloadReport, useReport, useReportReferences } from './api';

const today = new Date(); const monthAgo = new Date(today.getTime() - 29 * 86_400_000);
const types = [{ value: 'daily-patients', label: 'Daily patients' }, { value: 'revenue', label: 'Revenue' }, { value: 'doctors', label: 'Doctor activity' }, { value: 'pharmacy', label: 'Pharmacy' }, { value: 'inventory', label: 'Inventory' }, { value: 'appointments', label: 'Appointments' }, { value: 'cancellations', label: 'Cancellations' }];
export function ReportsPage() { const [type, setType] = useState('daily-patients'); const [dateFrom, setDateFrom] = useState(monthAgo.toISOString().slice(0, 10)); const [dateTo, setDateTo] = useState(today.toISOString().slice(0, 10)); const [doctorId, setDoctorId] = useState<string | null>(null); const [serviceId, setServiceId] = useState<string | null>(null); const filter = { dateFrom, dateTo, doctorId: doctorId ?? undefined, serviceId: serviceId ?? undefined }; const report = useReport(type, filter); const references = useReportReferences(); const exportCsv = async () => { try { await downloadReport(type, filter); notifications.show({ color: 'teal', message: 'CSV export downloaded.' }); } catch { notifications.show({ color: 'red', message: 'Unable to export this report.' }); } }; return <Stack><Group justify="space-between"><div><Title order={2}>Reports</Title><Text c="dimmed">Operational clinic reports with consistent on-screen and CSV data.</Text></div><Button leftSection={<IconDownload size={18}/>} onClick={() => void exportCsv()}>Export CSV</Button></Group><Paper withBorder p="md"><Group align="flex-end"><Select label="Report" value={type} onChange={(value) => setType(value ?? 'daily-patients')} data={types} w={200}/><TextInput label="From" type="date" value={dateFrom} onChange={(event) => setDateFrom(event.currentTarget.value)}/><TextInput label="To" type="date" value={dateTo} onChange={(event) => setDateTo(event.currentTarget.value)}/><Select clearable searchable label="Doctor" placeholder="All doctors" value={doctorId} onChange={setDoctorId} data={(references.doctors.data ?? []).map((doctor) => ({ value: doctor.id, label: doctor.fullName }))} w={220}/><Select clearable searchable label="Service" placeholder="All services" value={serviceId} onChange={setServiceId} data={(references.services.data ?? []).map((service) => ({ value: service.id, label: service.name }))} w={220}/></Group></Paper><Paper withBorder p="md">{report.isLoading ? <Center py={60}><Loader/></Center> : report.isError ? <Alert color="red">Unable to load report. Check the date range.</Alert> : report.data!.rows.length === 0 ? <Center py={60}><Text c="dimmed">No data for the selected filters.</Text></Center> : <Table.ScrollContainer minWidth={700}><Table striped highlightOnHover><Table.Thead><Table.Tr>{report.data!.columns.map((column) => <Table.Th key={column.key}>{column.label}</Table.Th>)}</Table.Tr></Table.Thead><Table.Tbody>{report.data!.rows.map((row, index) => <Table.Tr key={index}>{report.data!.columns.map((column) => <Table.Td key={column.key}>{String(row[column.key] ?? '')}</Table.Td>)}</Table.Tr>)}</Table.Tbody></Table></Table.ScrollContainer>}</Paper></Stack>; }
