import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { MantineProvider } from '@mantine/core';
import { Notifications } from '@mantine/notifications';
import '@mantine/core/styles.css';
import '@mantine/dates/styles.css';
import '@mantine/notifications/styles.css';
import { clinicTheme } from './app/theme/clinic-theme';
import { ClinicApp } from './ClinicApp';
createRoot(document.getElementById('root')!).render(<StrictMode><MantineProvider theme={clinicTheme} defaultColorScheme="light"><Notifications position="top-right"/><ClinicApp/></MantineProvider></StrictMode>);
