import { Alert, Badge, Button, Center, Group, Loader, Paper, Stack, Table, Text, Title } from '@mantine/core';
import { notifications } from '@mantine/notifications';
import { IconAlertCircle } from '@tabler/icons-react';
import { differenceInMinutes, differenceInYears } from 'date-fns';
import { useNavigate } from 'react-router-dom';
import { useSession } from '../../app/auth/session-store';
import { QueueEntry, useQueue, useQueueStatus, useStartVisit } from './api';

const clinicToday=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Makassar',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export function QueuePage(){const user=useSession(state=>state.user)!;const doctor=user.role==='DOCTOR';const today=clinicToday();const queue=useQueue(today);const update=useQueueStatus();const startVisit=useStartVisit();const navigate=useNavigate();const setStatus=async(id:string,status:string)=>{try{await update.mutateAsync({id,status});}catch{notifications.show({color:'red',title:'Queue update failed',message:'Refresh and try again.'});}};const start=async(entry:QueueEntry)=>{try{if(entry.visitId){navigate(`/doctor/consultations/${entry.visitId}`);return;}const visit=await startVisit.mutateAsync(entry.id);navigate(`/doctor/consultations/${visit.id}`);}catch{notifications.show({color:'red',message:'Unable to start consultation'});}};if(queue.isLoading)return <Center py={50}><Loader/></Center>;return <Stack><div><Title order={2}>Today&apos;s queue</Title><Text c="dimmed">Live outpatient check-in and consultation status.</Text></div><Paper withBorder radius="lg" p="md">{queue.isError?<Alert color="red" icon={<IconAlertCircle/>}>Unable to load the queue.</Alert>:queue.data!.length===0?<Center py={50}><Text c="dimmed">No patients are waiting.</Text></Center>:<Table.ScrollContainer minWidth={900}><Table striped highlightOnHover><Table.Thead><Table.Tr><Table.Th>Queue</Table.Th><Table.Th>Patient</Table.Th><Table.Th>Age / gender</Table.Th><Table.Th>Waiting</Table.Th><Table.Th>Status</Table.Th><Table.Th>Actions</Table.Th></Table.Tr></Table.Thead><Table.Tbody>{queue.data!.map(entry=><Table.Tr key={entry.id}><Table.Td><Text fw={700} size="lg" c="teal">{entry.queueNumber}</Text></Table.Td><Table.Td><Text fw={500}>{entry.patientName}</Text><Text size="xs" c="dimmed">{entry.mrn} · appointment {entry.startTime.slice(0,5)}</Text></Table.Td><Table.Td>{differenceInYears(new Date(),new Date(`${entry.dateOfBirth}T00:00:00`))} / {entry.gender}</Table.Td><Table.Td>{Math.max(0,differenceInMinutes(new Date(),new Date(entry.checkedInAt)))} min</Table.Td><Table.Td><Badge variant="light">{entry.status.replace(/_/g,' ')}</Badge></Table.Td><Table.Td><Group gap="xs">{doctor&&['WAITING','CALLED','IN_CONSULTATION'].includes(entry.status)?<Button size="xs" onClick={()=>void start(entry)}>{entry.status==='IN_CONSULTATION'?'Continue':'Start consultation'}</Button>:null}{!doctor&&entry.status==='WAITING'?<Button size="xs" onClick={()=>void setStatus(entry.id,'CALLED')}>Call</Button>:null}</Group></Table.Td></Table.Tr>)}</Table.Tbody></Table></Table.ScrollContainer>}</Paper></Stack>}
